[project]
name = "trypixi"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ralf Gommers <ralf.gommers@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
build = {cmd = "spin build", cwd = "pywt"}
test = {cmd = "spin test", cwd = "pywt"}
wheel = {cmd = "python -m build -wnx -Cbuild-dir=build-whl && cp dist/*.whl ../../wheelhouse/", cwd = "pywt"}

[dependencies]
compilers = ">=1.7.0,<2"
meson-python = ">=0.16.0,<0.17"
spin = ">=0.11,<0.12"
cython = ">=3.0.10,<4"
build = "*"
pytest = "*"
