[project]
name = "scipy"
version = "1.15.0.dev0"
description = "Fundamental algorithms for scientific computing in Python"
authors = ["SciPy Developers <scipy-dev@python.org>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
build = {cmd = "python dev.py build", cwd = "scipy"}
wheel = {cmd = "python -m build -wnx -Cbuild-dir=build-whl && cp dist/*.whl ../../wheelhouse/", cwd = "scipy"}

[dependencies]
compilers = ">=1.7.0,<2"
pkg-config = ">=0.29.2,<0.30"
ninja = ">=1.12.1,<2"
meson = ">=1.5.1,<2"
meson-python = ">=0.16.0"
openblas = ">=0.3.27,<0.4"
cython = ">=3.0.10,<4"
build = "*"
numpy = ">=2.0.0"
pybind11 = ">=2.13.1"
pythran = ">=0.15.0"
rich-click = "*"
pydevtool = "*"

[feature.test.dependencies]
pytest = "*"
hypothesis = "*"
pytest-cov = "*"
pytest-timeout = "*"
pytest-xdist = "*"
asv = "*"
threadpoolctl = "*"
pooch = "*"
mpmath = "*"
gmpy2 = "*"
mypy = "1.10.*"
typing_extensions = "*"
types-psutil = "*"

[feature.lint.dependencies]
ruff = "*"
pycodestyle = "*"
cython-lint = ">=0.12.2"


[feature.test.tasks]
test = {cmd = "python dev.py test", cwd = "scipy"}
mypy = {cmd = "python dev.py mypy", cwd = "scipy"}

[feature.lint.tasks]
lint = {cmd = "python dev.py lint", cwd = "scipy"}


# CPU/CUDA features
[feature.cpu]
platforms = ["linux-64", "osx-arm64"]

[feature.cpu.tasks]
test-cpu = {cmd = "python dev.py test -b all", cwd = "scipy"}

[feature.cuda]
platforms = ["linux-64"]
system-requirements = {cuda = "12"}

[feature.cuda.tasks]
test-cuda = {cmd = "python dev.py test -b all", cwd = "scipy"}


# Array libraries we have support for
[feature.pytorch]
platforms = ["linux-64", "osx-arm64"]

[feature.pytorch.dependencies]
pytorch = "*"

[feature.pytorch.tasks]
test-torch = {cmd = "python dev.py test -b pytorch", cwd = "scipy"}

[feature.cupy]
platforms = ["linux-64"]

[feature.cupy.dependencies]
cupy = "*"

[feature.cupy.tasks]
test-cupy = {cmd = "python dev.py test -b cupy", cwd = "scipy"}

[feature.jax]
platforms = ["linux-64", "osx-arm64"]

[feature.jax.dependencies]
jax = "*"

[feature.jax.tasks]
test-jax = {cmd = "python dev.py test -b jax.numpy", cwd = "scipy"}

[feature.array_api_strict]
platforms = ["linux-64", "osx-arm64"]

[feature.array_api_strict.dependencies]
array-api-strict = "*"

[feature.array_api_strict.tasks]
test-strict = {cmd = "python dev.py test -b array_api_strict", cwd = "scipy"}


[environments]
test = ["test"]
lint = ["lint"]
dev = ["test", "lint"]
default = ["test"]
pytorch = ["pytorch", "test"]
cupy = ["cupy", "test"]
jax = ["jax", "test"]
array-api-strict = ["array_api_strict", "test"]
array-api = ["cpu", "pytorch", "jax", "array_api_strict", "test"]
array-api-cuda = ["cuda", "pytorch", "jax", "cupy", "array_api_strict", "test"]
