[project]
name = "numpy"
version = "2.2.0.dev0"
description = "Fundamental package for array computing in Python"
authors = ["Ralf Gommers <ralf.gommers@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]
build = { cmd = "spin build", cwd = "numpy", env = { CC = "ccache $CC", CXX = "ccache $CXX" } }
ipython = { cmd = "spin ipython", cwd = "numpy" }
wheel = { cmd = "python -m build -wnx -Cbuild-dir=build-whl && mv dist/*.whl ../../wheelhouse/", cwd = "numpy" }

#[target.unix.activation.env]
#CC = "ccache $CC"

[dependencies]
compilers = ">=1.9.0,<2"
pkg-config = ">=0.29.2,<0.30"
ninja = ">=1.12.1,<2"
meson = ">=1.7.1,<2"
meson-python = ">=0.17.1,<0.18"
openblas = ">=0.3.29,<0.4"
spin = ">=0.13,<0.14"
cython = ">=3.0.12,<4"
python-build = ">=1.2.2.post1,<2"
ipython = ">=9.1.0,<10"
ccache = ">=4.11.2,<5"

[feature.test.dependencies]
pytest = "*"
hypothesis = "*"
pytest-xdist = "*"
asv = "*"
mypy = "==1.15.0"

[feature.lint.dependencies]
ruff = "*"
pycodestyle = "2.8.*"
gitpython = ">=3.1.30"


[feature.test.tasks]
test = { cmd = "spin test", cwd = "numpy" }
bench = { cmd = "spin bench", cwd = "numpy" }
mypy = { cmd = "spin mypy", cwd = "numpy" }

[feature.lint.tasks]
lint = { cmd = "spin lint", cwd = "numpy" }


[environments]
test = ["test"]
lint = ["lint"]
